# Generated by Django 5.2.15 on 2026-06-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'class_schedule',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.CharField(max_length=100)),
                ('expires_at', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.CharField(max_length=100)),
                ('class_schedule', models.ForeignKey(blank=True, db_column='class_schedule_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.classschedule')),
                ('class_schedule_old', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_legacy', to='attendance.classschedule')),
                ('section', models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.section')),
            ],
            options={
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.section'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=100)),
                ('section', models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.section')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('is_read', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=100)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='attendance.attendancesession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.user'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.user'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.CharField(max_length=100)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.attendancesession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.user')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
